/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hundirlaflota;

import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.*;
import java.security.*;
import java.util.logging.*;
import javax.swing.JDialog;
import javax.swing.WindowConstants;

/**
 *
 * @author harnick
 */
public class Register extends javax.swing.JDialog {
    
    private final String PASSWORD_PATTERN = "((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[&+*@#$%]).{8,24})";
    private static final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    private HundirLaFlota hlf;
    //private static final String EMAIL_PATTERN = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";

    /**
     * Creates new form Register
     */
    public Register(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabelContrasenaNoValida.setVisible(false);
        jLabelContrasenaNoCoincide.setVisible(false);
        jLabelEmailEnUso.setVisible(false);
        jLabelNickOcupado.setVisible(false);
        jLabelUsuarioExistente.setVisible(false);
        jLabelRegistroCorrecto.setVisible(false);
        KeyboardFocusManager kb = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        kb.addKeyEventPostProcessor(new KeyEventPostProcessor(){
            @Override
            public boolean postProcessKeyEvent(KeyEvent e){
                if(e.getKeyCode()==KeyEvent.VK_ESCAPE){
                    jButtonCancelar.doClick();
                }
                return true;
            }
        });
    }
    
    public boolean validaJButtonRegistrar(){
        if(!jTextFieldUsuario.getText().equals("")&&jTextFieldUsuario.getBackground().equals(new java.awt.Color(255, 255, 255))){
            if(!jTextFieldNick.getText().equals("")){
                if(!jPasswordField.getText().equals("")&&jPasswordField.getBackground().equals(new java.awt.Color(255, 255, 255))){
                    if(!jPasswordFieldRepetir.getText().equals("")&&jPasswordFieldRepetir.getBackground().equals(new java.awt.Color(255, 255, 255))){
                        if(!jTextFieldEmail.getText().equals("")&&jTextFieldEmail.getBackground().equals(new java.awt.Color(255, 255, 255))){
                            return true;
                        }else{
                            return false;
                        }
                    }else{
                        return false;
                    }
                }else{
                    return false;
                }
            }else{
                return false;
            }
        }else{
            return false;
        }
    }
    
    public boolean validaJButtonLimpiar(){
        if(!jTextFieldUsuario.getText().equals("")){
            return true;
        }
        if(!jTextFieldNick.getText().equals("")){
            return true;
        }
        if(!jPasswordField.getText().equals("")){
            return true;
        }
        if(!jPasswordFieldRepetir.getText().equals("")){
            return true;
        }
        if(!jTextFieldEmail.getText().equals("")){
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelContrasena = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelUsuarioExistente = new javax.swing.JLabel();
        jLabelIconSetting = new javax.swing.JLabel();
        jLabelContrasenaRepetir = new javax.swing.JLabel();
        jPasswordFieldRepetir = new javax.swing.JPasswordField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelNickOcupado = new javax.swing.JLabel();
        jLabelNick = new javax.swing.JLabel();
        jTextFieldNick = new javax.swing.JTextField();
        jLabelContrasenaNoValida = new javax.swing.JLabel();
        jLabelContrasenaNoCoincide = new javax.swing.JLabel();
        jLabelEmailEnUso = new javax.swing.JLabel();
        jLabelIconSetting1 = new javax.swing.JLabel();
        jLabelRegistroCorrecto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hundir La Flota Registro");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setToolTipText("");
        jButtonLimpiar.setAutoscrolls(true);
        jButtonLimpiar.setEnabled(false);
        jButtonLimpiar.setNextFocusableComponent(jButtonCancelar);
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.setAutoscrolls(true);
        jButtonRegistrar.setEnabled(false);
        jButtonRegistrar.setNextFocusableComponent(jButtonLimpiar);
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setAutoscrolls(true);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelContrasena.setText("Contraseña:");
        jLabelContrasena.setAutoscrolls(true);

        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });

        jLabelUsuario.setText("Usuario:");
        jLabelUsuario.setAutoscrolls(true);

        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });

        jLabelUsuarioExistente.setForeground(java.awt.Color.red);
        jLabelUsuarioExistente.setText("Usuario existente");

        jLabelIconSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SettingIcon.png"))); // NOI18N
        jLabelIconSetting.setToolTipText("<html>Tiene que tener 8-24 caracteres sin espacio<br>una mayuscula, un numero, y un caracter especial</html>");
        jLabelIconSetting.setAutoscrolls(true);

        jLabelContrasenaRepetir.setText("Repetir contraseña:");
        jLabelContrasenaRepetir.setAutoscrolls(true);

        jPasswordFieldRepetir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldRepetirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldRepetirFocusLost(evt);
            }
        });

        jLabelEmail.setText("Email:");
        jLabelEmail.setAutoscrolls(true);

        jTextFieldEmail.setNextFocusableComponent(jButtonRegistrar);
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });

        jLabelNickOcupado.setForeground(java.awt.Color.red);
        jLabelNickOcupado.setText("Nick ocupado");

        jLabelNick.setText("Nick:");
        jLabelNick.setAutoscrolls(true);

        jTextFieldNick.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNickFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNickFocusLost(evt);
            }
        });

        jLabelContrasenaNoValida.setForeground(java.awt.Color.red);
        jLabelContrasenaNoValida.setText("Contraseña no válida");

        jLabelContrasenaNoCoincide.setForeground(java.awt.Color.red);
        jLabelContrasenaNoCoincide.setText("Contraseña no coincide");

        jLabelEmailEnUso.setForeground(java.awt.Color.red);
        jLabelEmailEnUso.setText("Email en uso");

        jLabelIconSetting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SettingIcon.png"))); // NOI18N
        jLabelIconSetting1.setToolTipText("<html>Tiene que tener 8-24 caracteres sin espacio</html>");
        jLabelIconSetting1.setAutoscrolls(true);

        jLabelRegistroCorrecto.setForeground(java.awt.Color.red);
        jLabelRegistroCorrecto.setText("Registro correcto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelContrasenaRepetir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldRepetir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelContrasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNick)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNick))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUsuario))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLimpiar)
                            .addComponent(jLabelUsuarioExistente)
                            .addComponent(jLabelNickOcupado)
                            .addComponent(jLabelContrasenaNoCoincide)
                            .addComponent(jLabelContrasenaNoValida)
                            .addComponent(jLabelEmailEnUso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRegistroCorrecto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonRegistrar)
                                .addGap(46, 46, 46)
                                .addComponent(jButtonCancelar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIconSetting)
                    .addComponent(jLabelIconSetting1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUsuario)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUsuarioExistente))
                    .addComponent(jLabelIconSetting1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick)
                    .addComponent(jTextFieldNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNickOcupado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelContrasena)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelContrasenaNoValida))
                    .addComponent(jLabelIconSetting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContrasenaRepetir)
                    .addComponent(jPasswordFieldRepetir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelContrasenaNoCoincide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailEnUso)
                    .addComponent(jLabelRegistroCorrecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonRegistrar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        jLabelIconSetting.getAccessibleContext().setAccessibleDescription("<html>Tiene que tener 8-24 caracteres sin espacio<br>una mayuscula, un numero y un caracter especial</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        jTextFieldUsuario.setText("");
        jTextFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNick.setText("");
        jTextFieldNick.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField.setText("");
        jPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldRepetir.setText("");
        jPasswordFieldRepetir.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setText("");
        jTextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsuarioExistente.setVisible(false);
        jLabelNickOcupado.setVisible(false);
        jLabelContrasenaNoValida.setVisible(false);
        jLabelContrasenaNoCoincide.setVisible(false);
        jLabelEmailEnUso.setVisible(false);
        jButtonLimpiar.setEnabled(false);
        jLabelRegistroCorrecto.setVisible(false);
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        StringBuffer hexString = new StringBuffer();
        try {
            // Create MD5 Hash
            MessageDigest digest = java.security.MessageDigest.getInstance("MD5");
            digest.update(jPasswordField.getText().getBytes());
            byte messageDigest[] = digest.digest();

            for (int i=0; i<messageDigest.length; i++){
                hexString.append(Integer.toHexString(0xFF & messageDigest[i]));
            }

        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
        try {
            hlf = new HundirLaFlota();
            String res = hlf.execRegister(jTextFieldUsuario.getText(), hexString.toString(), jTextFieldNick.getText(), jTextFieldEmail.getText());
            if(res.equals("ok")){
                jButtonLimpiar.doClick();
                jLabelRegistroCorrecto.setVisible(true);
            }else{
                jLabelUsuarioExistente.setVisible(false);
                jLabelNickOcupado.setVisible(false);
                jLabelEmailEnUso.setVisible(false);
                String[] splitRes=res.split(" ");
                for(String x : splitRes){
                    System.out.println(x);
                    if(x.equals("user")){
                        jTextFieldUsuario.setText("");
                        jLabelUsuarioExistente.setVisible(true);
                    }else if(x.equals("nick")){
                        jLabelNickOcupado.setVisible(true);
                        jTextFieldNick.setText("");
                    }else if(x.equals("email")){
                        jTextFieldEmail.setText("");
                        jLabelEmailEnUso.setVisible(true);
                    }
                }
                jLabelRegistroCorrecto.setVisible(false);
            }

        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
        // TODO add your handling code here:
        jPasswordField.selectAll();
    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
        // TODO add your handling code here:
        if (!jPasswordField.getText().matches("(.*\\s.*)")&&jPasswordField.getText().matches(PASSWORD_PATTERN)){
            jPasswordField.setBackground(new java.awt.Color(255, 255, 255));
            jLabelContrasenaNoValida.setVisible(false);
        }else{
            jPasswordField.setBackground(java.awt.Color.red);
            jLabelContrasenaNoValida.setVisible(true);
        }
        if(validaJButtonLimpiar()){
            jButtonLimpiar.setEnabled(true);
        }else{
            jButtonLimpiar.setEnabled(false);
        }
        if(validaJButtonRegistrar()){
            jButtonRegistrar.setEnabled(true);
        }else{
            jButtonRegistrar.setEnabled(false);
        }
    }//GEN-LAST:event_jPasswordFieldFocusLost

    private void jTextFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusGained
        // TODO add your handling code here:
        jTextFieldUsuario.selectAll();
    }//GEN-LAST:event_jTextFieldUsuarioFocusGained

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
        // TODO add your handling code here:
        if (!jTextFieldUsuario.getText().matches("(.*\\s.*)")&&jTextFieldUsuario.getText().length()>7&&jTextFieldUsuario.getText().length()<25){
            jTextFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));
        }else{
            jTextFieldUsuario.setBackground(java.awt.Color.red);
        }
        if(validaJButtonLimpiar()){
            jButtonLimpiar.setEnabled(true);
        }else{
            jButtonLimpiar.setEnabled(false);
        }
        if(validaJButtonRegistrar()){
            jButtonRegistrar.setEnabled(true);
        }else{
            jButtonRegistrar.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jPasswordFieldRepetirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldRepetirFocusGained
        // TODO add your handling code here:
        jPasswordFieldRepetir.selectAll();
    }//GEN-LAST:event_jPasswordFieldRepetirFocusGained

    private void jTextFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusGained
        // TODO add your handling code here:
        jTextFieldEmail.selectAll();
    }//GEN-LAST:event_jTextFieldEmailFocusGained

    private void jTextFieldNickFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNickFocusGained
        // TODO add your handling code here:
        jTextFieldNick.selectAll();
    }//GEN-LAST:event_jTextFieldNickFocusGained

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        // TODO add your handling code here:
        if (jTextFieldEmail.getText().matches(EMAIL_PATTERN)){
            jTextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        }else{
            jTextFieldEmail.setBackground(java.awt.Color.red);
        }
        if(validaJButtonLimpiar()){
            jButtonLimpiar.setEnabled(true);
        }else{
            jButtonLimpiar.setEnabled(false);
        }
        if(validaJButtonRegistrar()){
            jButtonRegistrar.setEnabled(true);
        }else{
            jButtonRegistrar.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jPasswordFieldRepetirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldRepetirFocusLost
        // TODO add your handling code here:
        if (jPasswordField.getText().equals(jPasswordFieldRepetir.getText())){
            jPasswordFieldRepetir.setBackground(new java.awt.Color(255, 255, 255));
            jLabelContrasenaNoCoincide.setVisible(false);
        }else{
            jPasswordFieldRepetir.setBackground(java.awt.Color.red);
            jLabelContrasenaNoCoincide.setVisible(true);
        }
        if(validaJButtonLimpiar()){
            jButtonLimpiar.setEnabled(true);
        }else{
            jButtonLimpiar.setEnabled(false);
        }
        if(validaJButtonRegistrar()){
            jButtonRegistrar.setEnabled(true);
        }else{
            jButtonRegistrar.setEnabled(false);
        }
    }//GEN-LAST:event_jPasswordFieldRepetirFocusLost

    private void jTextFieldNickFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNickFocusLost
        // TODO add your handling code here:
        if(validaJButtonLimpiar()){
            jButtonLimpiar.setEnabled(true);
        }else{
            jButtonLimpiar.setEnabled(false);
        }
        if(validaJButtonRegistrar()){
            jButtonRegistrar.setEnabled(true);
        }else{
            jButtonRegistrar.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldNickFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelContrasena;
    private javax.swing.JLabel jLabelContrasenaNoCoincide;
    private javax.swing.JLabel jLabelContrasenaNoValida;
    private javax.swing.JLabel jLabelContrasenaRepetir;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmailEnUso;
    private javax.swing.JLabel jLabelIconSetting;
    private javax.swing.JLabel jLabelIconSetting1;
    private javax.swing.JLabel jLabelNick;
    private javax.swing.JLabel jLabelNickOcupado;
    private javax.swing.JLabel jLabelRegistroCorrecto;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelUsuarioExistente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordFieldRepetir;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNick;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
